# Generated by Django 3.1.2 on 2020-12-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qnty',
            field=models.IntegerField(),
        ),
    ]
