# Generated by Django 3.1.2 on 2020-12-03 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_auto_20201202_1304'),
        ('checkout', '0003_order_ordersummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product_full'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
