# Generated by Django 3.1.2 on 2020-12-02 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_remove_product_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_full',
            name='slug',
        ),
        migrations.AddField(
            model_name='product_review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
