# Generated by Django 3.1.2 on 2020-12-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201202_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_full',
            name='p_specs_short',
        ),
        migrations.AddField(
            model_name='product_full',
            name='cpu',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_full',
            name='gpu',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_full',
            name='memory',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_full',
            name='op_sys',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_full',
            name='p_brand',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_full',
            name='ram',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_full',
            name='screen_res',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_full',
            name='screen_size',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_full',
            name='typ',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_full',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_full',
            name='p_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product_full',
            name='p_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Accessories', 'Accessories'), ('Software', 'Software')], max_length=30),
        ),
    ]
