# Generated by Django 3.1.2 on 2020-11-27 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201127_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.product_full'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_review',
            name='s_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
