# Generated by Django 3.1.2 on 2020-11-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20201128_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_review',
            name='user',
        ),
        migrations.DeleteModel(
            name='checkout',
        ),
        migrations.DeleteModel(
            name='product_full',
        ),
        migrations.DeleteModel(
            name='product_review',
        ),
    ]
